<?php
/**
 * ResultSelection
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIW API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.24
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ResultSelection Class Doc Comment
 *
 * @category Class
 * @description Specifies ways to obtain the result.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResultSelection
{
    /**
     * Possible values of this enum
     */
    const RESULT_SELECTION_UNDEFINED = 'RESULT_SELECTION_UNDEFINED';
const USER_CHOICE = 'USER_CHOICE';
const PRESELECTED_CHOICE = 'PRESELECTED_CHOICE';
const FALLBACK_FROM_USER_CHOICE = 'FALLBACK_FROM_USER_CHOICE';
const FALLBACK_FROM_PRESELECTED_CHOICE = 'FALLBACK_FROM_PRESELECTED_CHOICE';
const FALLBACK_FAILED_FOR_USER_CHOICE = 'FALLBACK_FAILED_FOR_USER_CHOICE';
const FALLBACK_FAILED_FOR_PRESELECTED_CHOICE = 'FALLBACK_FAILED_FOR_PRESELECTED_CHOICE';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RESULT_SELECTION_UNDEFINED,
self::USER_CHOICE,
self::PRESELECTED_CHOICE,
self::FALLBACK_FROM_USER_CHOICE,
self::FALLBACK_FROM_PRESELECTED_CHOICE,
self::FALLBACK_FAILED_FOR_USER_CHOICE,
self::FALLBACK_FAILED_FOR_PRESELECTED_CHOICE,        ];
    }
}
