<?php
/**
 * ResultSelection
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIW API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.26
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ResultSelection Class Doc Comment
 *
 * @category Class
 * @description Specifies ways to obtain the result.   - RESULT_SELECTION_UNDEFINED: Delivery Checkout failed to compute the selection reason for the delivery option use.  - USER_CHOICE: Delivery option selection was done by the end user.  - PRESELECTED_CHOICE: The preselected delivery option was used for selection. End user did not change delivery option from what was preselected.  - FALLBACK_FROM_USER_CHOICE: The user choice could not be respected when completing the session. Eg. due to carrier not covering the delivery address used for completing the session.  - FALLBACK_FROM_PRESELECTED_CHOICE: The preselected choice could not be respected when completing the session. Eg. due to carrier not covering the delivery address used for completing the session.  - FALLBACK_FAILED_FOR_USER_CHOICE: Selection was made based on user choice and fallback failing.  - FALLBACK_FAILED_FOR_PRESELECTED_CHOICE: Selection was made based on preselected choice and fallback failing.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResultSelection
{
    /**
     * Possible values of this enum
     */
    const RESULT_SELECTION_UNDEFINED = 'RESULT_SELECTION_UNDEFINED';
    const USER_CHOICE = 'USER_CHOICE';
    const PRESELECTED_CHOICE = 'PRESELECTED_CHOICE';
    const FALLBACK_FROM_USER_CHOICE = 'FALLBACK_FROM_USER_CHOICE';
    const FALLBACK_FROM_PRESELECTED_CHOICE = 'FALLBACK_FROM_PRESELECTED_CHOICE';
    const FALLBACK_FAILED_FOR_USER_CHOICE = 'FALLBACK_FAILED_FOR_USER_CHOICE';
    const FALLBACK_FAILED_FOR_PRESELECTED_CHOICE = 'FALLBACK_FAILED_FOR_PRESELECTED_CHOICE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RESULT_SELECTION_UNDEFINED,
            self::USER_CHOICE,
            self::PRESELECTED_CHOICE,
            self::FALLBACK_FROM_USER_CHOICE,
            self::FALLBACK_FROM_PRESELECTED_CHOICE,
            self::FALLBACK_FAILED_FOR_USER_CHOICE,
            self::FALLBACK_FAILED_FOR_PRESELECTED_CHOICE,
        ];
    }
}


