<?php
/**
 * ShippingPickupLocationType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SIW API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * ShippingPickupLocationType Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShippingPickupLocationType
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN_PICKUP_LOCATION_TYPE = 'UNKNOWN_PICKUP_LOCATION_TYPE';
    const LOCKER = 'LOCKER';
    const STORE = 'STORE';
    const POSTOFFICE = 'POSTOFFICE';
    const MANNED = 'MANNED';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN_PICKUP_LOCATION_TYPE,
            self::LOCKER,
            self::STORE,
            self::POSTOFFICE,
            self::MANNED,
        ];
    }
}


